### ISSUE TITLE
prefixの`/`が原因で認識されない

### ISSUE THREAD

**Issue by yki-t** [ToMGitHubN/gcs-basic-auth#6]
次のようなバケットがある場合、

```
gs://someobejct/abc/def.html
```

objectの指定は `someobject/abc/def.html` が正解ではないでしょうか？
今のままだと `/someobject/abc/def.html`になって、私の環境では404になりました。
一応手元では↑関連を諸々修正したら正常に稼働してくれているのですが、
どうでしょうか？

**Comment by ToMGitHubN** [comment]
@yki-t  issueありがとうございます。
指摘されていた問題確認しました。
修正対応しましたので確認頂けると幸いです。

96aa9b97e1fdd83f19eab584af9eed15338568fc

5a6676100893f3f118b13d6bb066e61917977fe3

**Comment by yki-t** [comment]
ありがとうございます！
